# Task 1 — Data Cleaning & Preprocessing

In [1]:
# Import Libraries
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Sales_Dataset.csv")

In [3]:
df.head() # First 5 rows

,Order_ID,Order_Date,Customer_Name,Product,Category,Quantity,Unit_Price,Sales,Region,Payment_Method
0,ORD0001,2026-04-03,Neha Sharma,Desk Chair,Furniture,4.0,7500.0,30000,North,Bank Transfer
1,ORD0002,2026-03-16,Neha Sharma,Desk Chair,Furniture,2.0,7500.0,15000,North,UPI
2,ORD0003,2026-05-30,Vikram Gupta,Office Desk,Furniture,3.0,11000.0,33000,South,UPI
3,ORD0004,2026-07-11,Vikram Gupta,Printer,Electronics,2.0,9000.0,18000,North,UPI
4,ORD0005,2026-03-30,Aarav Sharma,USB Drive,Accessories,6.0,700.0,4200,East,Debit Card

In [4]:
# Shape
df.shape

(103, 10)

In [5]:
# Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        103 non-null    str
 1   Order_Date      103 non-null    str
 2   Customer_Name   102 non-null    str
 3   Product         102 non-null    str
 4   Category        103 non-null    str
 5   Quantity        102 non-null    float64
 6   Unit_Price      102 non-null    float64
 7   Sales           103 non-null    int64
 8   Region          102 non-null    str
 9   Payment_Method  102 non-null    str
dtypes: float64(2), int64(1), str(7)
memory usage: 8.2 KB

In [6]:
# check last 5 rows
df.tail()

,Order_ID,Order_Date,Customer_Name,Product,Category,Quantity,Unit_Price,Sales,Region,Payment_Method
98,ORD0099,2026-03-17,Karan Mehta,Webcam,Electronics,3.0,3500.0,10500,East,UPI
99,ORD0100,2026-04-21,Vikram Gupta,Monitor,Electronics,3.0,12000.0,36000,,Debit Card
100,ORD0011,2026-04-14,Sneha Patel,Monitor,Electronics,2.0,12000.0,24000,South,Credit Card
101,ORD0036,2026-07-06,Aarav Sharma,Office Desk,Furniture,1.0,11000.0,11000,South,Credit Card
102,ORD0071,2026-07-15,Ananya Jain,Headphones,Accessories,7.0,2500.0,17500,North,UPI

In [7]:
# Check Missing Values
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     1
Product           1
Category          0
Quantity          1
Unit_Price        1
Sales             0
Region            1
Payment_Method    1
dtype: int64

In [10]:
# Missing Value Percentage:
df.isnull().sum() / len(df) * 100

Order_ID          0.000000
Order_Date        0.000000
Customer_Name     0.970874
Product           0.970874
Category          0.000000
Quantity          0.970874
Unit_Price        0.970874
Sales             0.000000
Region            0.970874
Payment_Method    0.970874
dtype: float64

In [12]:
# Check Duplicate Rows
df.duplicated().sum()

np.int64(3)

In [13]:
df[df.duplicated()]

,Order_ID,Order_Date,Customer_Name,Product,Category,Quantity,Unit_Price,Sales,Region,Payment_Method
100,ORD0011,2026-04-14,Sneha Patel,Monitor,Electronics,2.0,12000.0,24000,South,Credit Card
101,ORD0036,2026-07-06,Aarav Sharma,Office Desk,Furniture,1.0,11000.0,11000,South,Credit Card
102,ORD0071,2026-07-15,Ananya Jain,Headphones,Accessories,7.0,2500.0,17500,North,UPI

In [14]:
# Remove Duplicate Rows
df = df.drop_duplicates()

print("Duplicates removed successfully!")

Duplicates removed successfully!

In [16]:
df.shape

(100, 10)

In [17]:
# Handle Blank/Space Values
df = df.replace(r'^\s*$', np.nan, regex=True)

print("Blank values converted to NaN.")

Blank values converted to NaN.

In [19]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     2
Product           1
Category          0
Quantity          1
Unit_Price        1
Sales             0
Region            2
Payment_Method    1
dtype: int64

In [21]:
# Clean Text Columns
text_columns = [
    "Customer_Name",
    "Product",
    "Category",
    "Region",
    "Payment_Method"
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [22]:
# Standardize Category Values
df["Category"] = df["Category"].str.title()

df["Category"].value_counts()

Category
Electronics    42
Accessories    41
Furniture      17
Name: count, dtype: int64

In [24]:
# Standardize Region
df["Region"] = df["Region"].str.title()

df["Region"].value_counts()

Region
West     28
South    26
North    24
East     20
Name: count, dtype: int64

In [25]:
# Standardize Payment Method
df["Payment_Method"] = df["Payment_Method"].str.title()

df["Payment_Method"].value_counts()

Payment_Method
Upi              25
Cash             24
Bank Transfer    17
Debit Card       17
Credit Card      16
Name: count, dtype: int64

In [26]:
df["Payment_Method"] = df["Payment_Method"].replace({
    "Upi": "UPI",
    "Credit card": "Credit Card",
    "Debit card": "Debit Card",
    "Bank transfer": "Bank Transfer"
})

In [27]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")

df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")

In [28]:
df[["Quantity", "Unit_Price", "Sales"]].dtypes

Quantity      float64
Unit_Price    float64
Sales           int64
dtype: object

In [30]:
# Convert Date Column
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)
df["Order_Date"].dtype

dtype('<M8[us]')

In [32]:
# Handle Missing Values
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     2
Product           1
Category          0
Quantity          1
Unit_Price        1
Sales             0
Region            2
Payment_Method    1
dtype: int64

In [33]:
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)

df["Unit_Price"] = df["Unit_Price"].fillna(
    df["Unit_Price"].median()
)

In [34]:
categorical_columns = [
    "Customer_Name",
    "Product",
    "Category",
    "Region",
    "Payment_Method"
]

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [36]:
# Recalculate Sales
df["Sales"] = df["Quantity"] * df["Unit_Price"]

In [39]:
# Check Data Types Again
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    str
 1   Order_Date      100 non-null    datetime64[us]
 2   Customer_Name   100 non-null    str
 3   Product         100 non-null    str
 4   Category        100 non-null    str
 5   Quantity        100 non-null    float64
 6   Unit_Price      100 non-null    float64
 7   Sales           100 non-null    float64
 8   Region          100 non-null    str
 9   Payment_Method  100 non-null    str
dtypes: datetime64[us](1), float64(3), str(6)
memory usage: 7.9 KB

In [40]:
# Check Missing Values Again
print("Missing values after cleaning:")
df.isnull().sum()

Missing values after cleaning:

Order_ID          0
Order_Date        0
Customer_Name     0
Product           0
Category          0
Quantity          0
Unit_Price        0
Sales             0
Region            0
Payment_Method    0
dtype: int64

In [41]:
# Check Duplicates Again
print("Duplicates after cleaning:")
df.duplicated().sum()

Duplicates after cleaning:

np.int64(0)

In [42]:
# Check Final Dataset
df.shape

(100, 10)

In [43]:
df.head()

,Order_ID,Order_Date,Customer_Name,Product,Category,Quantity,Unit_Price,Sales,Region,Payment_Method
0,ORD0001,2026-04-03,Neha Sharma,Desk Chair,Furniture,4.0,7500.0,30000.0,North,Bank Transfer
1,ORD0002,2026-03-16,Neha Sharma,Desk Chair,Furniture,2.0,7500.0,15000.0,North,UPI
2,ORD0003,2026-05-30,Vikram Gupta,Office Desk,Furniture,3.0,11000.0,33000.0,South,UPI
3,ORD0004,2026-07-11,Vikram Gupta,Printer,Electronics,2.0,9000.0,18000.0,North,UPI
4,ORD0005,2026-03-30,Aarav Sharma,USB Drive,Accessories,6.0,700.0,4200.0,East,Debit Card

In [ ]:
# Save Cleaned Dataset
df.to_csv(
    "data/cleaned/CodNova_Task1_Sales_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")